export const PERMISSIONS = {
  USER_VIEW: "USER_VIEW",
  USER_CREATE: "USER_CREATE",
  USER_UPDATE: "USER_UPDATE",
  USER_DELETE: "USER_DELETE",

  UPLOAD_DATA: "UPLOAD_DATA",
  COMPILE_INDEX: "COMPILE_INDEX",
  APPROVE_INDEX: "APPROVE_INDEX",
} as const;

export type Permission =
  typeof PERMISSIONS[keyof typeof PERMISSIONS];